---
language: python
services: docker

env:
  global:
    - ROLE_NAME: rpm-repository
  matrix:
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd
      ANSIBLE_VERSION:
install:
  # Install test dependencies.
  - pip install molecule==2.19 ansible==2.7.11 docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
