---
- name: Install packages for repository creation
  yum:
    name: "{{ item.name }}"
    state: present
  with_items:
    - name: createrepo
    - name: rpm-build
    - name: policycoreutils-python
    - name: setools-console
    - name: httpd
    - name: setools-console
    - name: libselinux-python
    - name: mod_ssl
    - name: repoview

- name: Ensure that paths for all architecture and version exists
  file:
    path: "{{ rpm_repository_path }}/{{ item.0 }}/{{ item.1 }}/{{ item.2 }}"
    state: directory
    mode: 0750
    owner: apache
    group: apache
    recurse: true
  with_nested:
    - "{{ rpm_repository_os }}"
    - "{{ rpm_repository_os_architecture }}"
    - "{{ rpm_repository_os_version }}"

- name: Create repo for all architecture and version
  command: "createrepo {{ rpm_repository_path }}/{{ item.0 }}/{{ item.1 }}/{{ item.2 }}"
  with_nested:
    - "{{ rpm_repository_os }}"
    - "{{ rpm_repository_os_architecture }}"
    - "{{ rpm_repository_os_version }}"
  changed_when: false

- name: Copy GPG key into apache
  copy:
    src: "/etc/pki/rpm-gpg/RPM-GPG-KEY-{{ rpm_repository_name }}"
    dest: "{{ rpm_repository_path }}/RPM-GPG-KEY-{{ rpm_repository_name }}"
    owner: apache
    group: apache
    mode: 0644
    remote_src: true
  changed_when: false

- name: Templating apache repository config file
  template:
    src: templates/repo.conf.j2
    dest: "/etc/httpd/conf.d/repo.conf"
    owner: root
    group: root
    mode: 0644

- name: Ensure that repo path exists
  file:
    path: "{{ rpm_repository_path }}/"
    state: directory
    mode: 0750
    owner: apache
    group: apache
    recurse: true
  changed_when: false

- name: Ensure that Apache is started
  service:
    name: httpd
    state: restarted

- name: Ensure that CRON directory exists
  file:
    path: /etc/cron.d
    state: directory

- name: Create cron task for metadata
  cron:
    name: createrepo
    special_time: hourly
    user: root
    job: "createrepo -d {{ rpm_repository_path }} > /dev/null"
    cron_file: createrepo

- name: Create cron task for metadata update
  cron:
    name: repoview_metadata_update
    special_time: hourly
    user: root
    job: "repoview {{ rpm_repository_path }} > /dev/null"
    cron_file: repoview

- name: Create cron task for static view update
  cron:
    name: repoview_static_view_update
    special_time: hourly
    user: root
    job: "repoview -d {{ rpm_repository_path }} > /dev/null"
    cron_file: repoview
