---
- name: Converge
  hosts: all
  become: true
  vars:
    rpm_repository_name: test
    rpm_repository_mail: test@test.com
    rpm_repository_os:
      - Centos
    rpm_repository_os_architecture:
      - x86_64
      - x86
    rpm_repository_os_version:
      - 6
      - 7
    rpm_repository_path: /var/www/html
    rpm_repository_regenerate_gpg_key: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: vahubert.apache
    - role: rpm-repository
