#!/usr/bin/expect -f

### delete-secret-keys

spawn gpg2 --quiet --delete-secret-keys {*}$argv
expect -exact "Delete this key from the keyring? (y/N)"
send -- "y\r"
expect -exact "This is a secret key! - really delete? (y/N)"
send -- "y\r"
expect eof

## end of delete-secret-keys
