---
- hosts: all
  become: yes
  pre_tasks:
  - name: Ensure build dependencies are installed (RedHat)
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "@Development tools"
      - tar
      - unzip
      - sudo
      - which
    when: ansible_os_family == 'RedHat'

  - name: Ensure build dependencies are installed (Debian)
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - unzip
      - tar
      - sudo
    when: ansible_os_family == 'Debian'
  roles:
    - vahubert.rpm-repository
  vars:
    path_repo: /share/CentOS
    path_repo_base: "{{ path_repo }}/6/local"
    path_repo_rpm: "{{ path_repo_base }}/x86_64"
    path_httpd_repo: /var/www/html
    path_httpd_repo_full : "{{ path_httpd_repo }}/CentOS"
    yum_repo_name: ngi-test
    yum_repo_mail: it@ngigroup.fr
    httpd_conf_dir: /etc/httpd/conf.d/
    always_regenerate_key: true
